core: api: requests: add retry strategy
When querying SQUAD the following Traceback was seen:

Traceback (most recent call last):
  File "/home/anders/src/squad-client-utils/./squad-stats-report", line 437, in <module>
    sys.exit(run())
  File "/home/anders/src/squad-client-utils/./squad-stats-report", line 363, in run
    devs = get_devices(environments, project.suites(count=ALL), builds)
  File "/home/anders/src/squad-client-utils/./squad-stats-report", line 249, in get_devices
    for s in testrun.statuses(suite__isnull=False).values():
  File "/home/anders/src/squad-client/squad_client/core/models.py", line 717, in statuses
    return self.__fetch__(TestRunStatus, filters, count)
  File "/home/anders/src/squad-client/squad_client/core/models.py", line 114, in __fetch__
    response = SquadApi.get(url, filters)
  File "/home/anders/src/squad-client/squad_client/core/api.py", line 78, in get
    return SquadApi.__request__('GET', endpoint, params=params)
  File "/home/anders/src/squad-client/squad_client/core/api.py", line 135, in __request__
    raise ApiException('Error Connecting: %s' % e)
squad_client.core.api.ApiException: Error Connecting: HTTPSConnectionPool(host='qa-reports.linaro.org', port=443): Max retries exceeded with url: /api/testruns/12470326/status/?suite__isnull=False&limit=1000 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0eb84a5960>: Failed to establish a new connection: [Errno -2] Name or service not known'))

Adding a retry strategy when the request fails, should fix issues like
this.

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>